# Generated by Django 4.2.4 on 2023-08-05 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vereador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vereador', models.CharField(max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(choices=[(0, 'Inexistente'), (1, 'Sim'), (2, 'Não'), (3, 'Abster')], default=0)),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.pauta')),
                ('vereador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.vereador')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.BooleanField(default=False)),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.reuniao')),
                ('vereador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.vereador')),
            ],
        ),
        migrations.AddField(
            model_name='pauta',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas', to='votacao.reuniao'),
        ),
    ]
