# Generated by Django 4.2.4 on 2023-08-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vereador',
            name='partido_politico',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
