# Generated by Django 4.2.4 on 2023-08-22 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votacao', '0003_vereador_data_nascimento_vereador_nome_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vereador',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
