# Generated by Django 4.2.4 on 2023-08-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0004_alter_vereador_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vereador',
            name='foto',
            field=models.ImageField(null=True, upload_to='vereadores_fotos/'),
        ),
    ]
