# Generated by Django 4.2.4 on 2023-08-23 11:06

from django.db import migrations, models
import os
from django.conf import settings

def add_fotos_to_vereadores(apps, schema_editor):
    Vereador = apps.get_model('votacao', 'Vereador')

    for vereador in Vereador.objects.all():
        foto_path = os.path.join(settings.MEDIA_ROOT, 'vereadores_fotos', f'{vereador.id}.jpg')
        if os.path.exists(foto_path):
            vereador.foto = f'vereadores_fotos/{vereador.id}.jpg'
            vereador.save()
            
def remove_fotos_from_vereadores(apps, schema_editor):
    # Esta função pode ser deixada vazia se você simplesmente quer permitir a reversão
    # sem realmente fazer nada. 
    # No entanto, se você precisar desfazer qualquer coisa específica, coloque o código aqui.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0005_vereador_foto'),
    ]

    operations = [
        migrations.RunPython(add_fotos_to_vereadores, remove_fotos_from_vereadores),

    ]
