# Generated by Django 4.2.4 on 2023-08-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0006_add_fotos_to_vereadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='vereador',
            name='partido_nome',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
