# Generated by Django 4.2.4 on 2023-09-01 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0007_vereador_partido_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoPolitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('nome_partido', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='vereador',
            name='partido_nome',
        ),
        migrations.RemoveField(
            model_name='vereador',
            name='partido_politico',
        ),
        migrations.AddField(
            model_name='vereador',
            name='partido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votacao.partidopolitico'),
        ),
    ]
