# Generated by Django 4.2.4 on 2023-09-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0008_partidopolitico_remove_vereador_partido_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidopolitico',
            name='nome_partido',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partidopolitico',
            name='sigla',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
