# Generated by Django 4.2.4 on 2023-09-02 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0009_alter_partidopolitico_nome_partido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vereador',
            name='partido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='votacao.partidopolitico'),
        ),
    ]
