# Generated by Django 4.2.4 on 2023-09-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0010_alter_vereador_partido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='presenca',
        ),
    ]
