# Generated by Django 4.2.4 on 2023-09-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0011_remove_presenca_presenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaDiretora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mesa', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='presenca',
            name='presenca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vereador',
            name='funcao_mesa_diretora',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vereador',
            name='partido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votacao.partidopolitico'),
        ),
        migrations.AddField(
            model_name='vereador',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votacao.mesadiretora'),
        ),
    ]
