# Generated by Django 4.2.4 on 2023-09-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0013_mesadiretora_data_fim_mesadiretora_data_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosVotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parametro', models.CharField(max_length=255)),
                ('quorun_aprovacao', models.IntegerField()),
                ('quorun_validacao', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pauta',
            name='parametros_votacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautas', to='votacao.parametrosvotacao'),
        ),
    ]
