# Generated by Django 4.2.4 on 2023-09-05 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0014_parametrosvotacao_pauta_parametros_votacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_acao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Prejudicada', 'Prejudicada'), ('Aprovada', 'Aprovada'), ('Reprovada', 'Reprovada'), ('Empatada', 'Empatada')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pauta',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautas', to='votacao.tipoacao'),
        ),
    ]
