# Generated by Django 4.2.4 on 2023-09-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0015_tipoacao_pauta_resultado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reuniao',
            old_name='data_hora',
            new_name='data_prevista',
        ),
        migrations.AddField(
            model_name='reuniao',
            name='numero_reuniao',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='tipo_reuniao',
            field=models.CharField(blank=True, choices=[('Ordinária', 'Ordinária'), ('Extraordinária', 'Extraordinária'), ('Especial', 'Especial'), ('Eleição', 'Eleição'), ('Solene', 'Solene'), ('Debate', 'Debate'), ('Preparatoria', 'Preparatoria'), ('Conjunta', 'Conjunta'), ('Regional', 'Regional'), ('Plénario', 'Plénario'), ('Outro', 'Outro')], max_length=20, null=True),
        ),
    ]
