# Generated by Django 4.2.4 on 2023-09-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0016_rename_data_hora_reuniao_data_prevista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='status',
            field=models.CharField(choices=[('Prevista', 'Prevista'), ('Aberta', 'Aberta'), ('Realizada', 'Realizada')], default='Prevista', max_length=10),
        ),
    ]
