# Generated by Django 4.2.4 on 2023-09-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0017_reuniao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='data_realizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pauta',
            name='status_votacao',
            field=models.CharField(choices=[('Prevista', 'Prevista'), ('Aberta', 'Aberta'), ('Realizada', 'Realizada')], default='Prevista', max_length=10),
        ),
        migrations.AlterField(
            model_name='tipoacao',
            name='categoria',
            field=models.CharField(choices=[('Prejudicada', 'Prejudicada'), ('Aprovada', 'Aprovada'), ('Reprovada', 'Reprovada'), ('Empatada', 'Empatada'), ('Não Realizada', 'Não Realizada'), ('Em Andamento', 'Em Andamento')], max_length=20),
        ),
    ]
