# Generated by Django 4.2.4 on 2023-09-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0018_pauta_data_realizacao_pauta_status_votacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='ementa',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
