# Generated by Django 4.2.4 on 2023-09-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0019_pauta_ementa'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='reuniao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votacao.reuniao'),
        ),
    ]
