# Generated by Django 4.2.4 on 2023-09-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0020_voto_reuniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='voto',
            field=models.CharField(choices=[('Inexistente', 'Inexistente'), ('Sim', 'Sim'), ('Não', 'Não'), ('Abster', 'Abster')], default='Inexistente', max_length=15),
        ),
    ]
