# Generated by Django 4.2.4 on 2023-10-05 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('votacao', '0021_alter_voto_voto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atual', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='voto',
            name='voto',
            field=models.CharField(choices=[('Inexistente', 'Inexistente'), ('Sim', 'Sim'), ('Nao', 'Nao'), ('Abster', 'Abster')], default='Inexistente', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('vereador', 'pauta'), name='unique_vereador_pauta'),
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
