# Generated by Django 4.2.4 on 2023-10-05 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0022_groupconfig_alter_voto_voto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupconfig',
            old_name='group',
            new_name='groupo',
        ),
    ]
