# Generated by Django 4.2.4 on 2023-10-05 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0023_rename_group_groupconfig_groupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupconfig',
            old_name='groupo',
            new_name='grupo',
        ),
    ]
