# Generated by Django 4.2.4 on 2023-10-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0024_rename_groupo_groupconfig_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidopolitico',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo_partido/'),
        ),
    ]
