# Generated by Django 4.2.6 on 2023-12-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0027_pauta_autor_pauta_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='resultado_categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
