# Generated by Django 4.2.6 on 2024-02-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0028_pauta_resultado_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='data_presenca',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
